version: "2"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/src/
    tty: true
    ports:
      - "5001:5000"
    command: python /src/run.py
  # admin:
  #   build:
  #     context: ./REST_admin/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/src/
  #     - ./SQL:/src/REST_admin/database/
  #   tty: true
  #   ports:
  #     - 6006:8000
  #   command: python3 /src/REST_admin/manage.py runserver 0.0.0.0:8000
