version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/src/
      - Files/:/Files/:rw
      - ./.ssh/:/root/.ssh/
    tty: true
    ports:
      - 15001:5000
    command: python /src/run.py
    restart: always

  plupload:
    build:
      context: ./plupload/
      dockerfile: Dockerfile
    volumes:
      - ./plupload/:/var/www/html/
      - Files/:/Files/:rw
      - ./.ssh/:/var/www/.ssh/
      - ./.ssh/:/root/.ssh/      
    ports:
      - 17001:80
    restart: always

  admin_metastorm:
    build:
      context: ./REST_admin/
      dockerfile: Dockerfile
    volumes:
      - ./:/src/
      - ./SQL:/src/REST_admin/database/
    tty: true
    ports:
      - 16001:8000
    command: python3 /src/REST_admin/manage.py runserver 0.0.0.0:8000
    restart: always

volumes:
  Files: